env:
  browser: true
  es6: true
  jest/globals: true
extends:
  - 'eslint:recommended'
  - 'standard'
  - 'standard-react'
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - jest
  - babel
rules:
  no-console: 0
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
